### ISSUE TITLE
In-order successor API

### ISSUE THREAD

**Issue by kiranns** [s-yata/louds-trie#1]
Hello Yata-san,

I am thinking of using your LOUDS trie implementation for our research prototype. Our requirements are slightly different, I need these modifications:

0. All keys are uint64_t values.
1. next(x)/successor(x) - Searches for x, if found returns x, otherwise returns the next highest (in-order) value higher than x.
2. Works with unsorted input keys.
3.  Should be able to store a value associated with a key. Potentially, on a different data structure that is also space-efficient.

Please let me know if you can help me with these modifications.

Regards,
Kiran

**Comment by s-yata** [comment]
Sorry, I have no plan to add new APIs.
This is just a simple implementation.
